import ReviewHistory from "@/components/ReviewHistory";
import ReviewNew from "@/components/ReviewNew";
import ReviewSearch from "@/components/ReviewSearch";
import { useSyncStore } from "@/hooks";
import Head from "next/head";

export default function Home() {
  useSyncStore();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ReviewNew />
        <ReviewSearch />
        <ReviewHistory />
      </main>
    </>
  );
}
